// lessonsData.js

export const MODULES_META = [
  { id: 1, title: "Fundamentos de Mercado", color: "#3B82F6", totalLessons: 25 },
  { id: 2, title: "Price Action Básico", color: "#10B981", totalLessons: 25 },
  { id: 3, title: "Padrões de Candlestick", color: "#8B5CF6", totalLessons: 25 },
  { id: 4, title: "Indicadores Técnicos", color: "#F59E0B", totalLessons: 25 },
  { id: 5, title: "Gestão & Psicotrader", color: "#EF4444", totalLessons: 25 },
];

export const LESSON_TITLES = {
  // Módulo 1 (1-25)
  "1-0": "O que são Opções Binárias?",
  "1-1": "Como funciona o Payout?",
  "1-2": "CALL vs. PUT na Prática",
  "1-3": "Tempo de Expiração (1m, 5m, 15m)",
  "1-4": "Prática: Entradas CALL e PUT",
  "1-5": "Mercado Aberto vs. OTC",
  "1-6": "Paridades de Moedas Majors",
  "1-7": "Como Ler Pares de Moedas",
  "1-8": "Tipos de Gráficos",
  "1-9": "Anatomia do Candlestick",
  "1-10": "Velas Verdes vs. Vermelhas",
  "1-11": "O Significado dos Pavios",
  "1-12": "Vantagem Estatística no Trading",
  "1-13": "Spread, Slippage e Taxas",
  "1-14": "Execução de Ordens em Segundos",
  "1-15": "Diferença entre Forex e Binárias",
  "1-16": "Sessões Globais de Negociação",
  "1-17": "Compreendendo a Volatilidade",
  "1-18": "Calendário Econômico e Notícias",
  "1-19": "Protegendo-se em Dias de Notícias",
  "1-20": "Conta Demo vs. Conta Real",
  "1-21": "Prática: Leitura Rápida de Velas",
  "1-22": "Configurando seu Gráfico",
  "1-23": "Revisão Geral de Fundamentos",
  "1-24": "Simulação Final de Mercado M1",

  // Módulo 2 (26-50)
  "2-0": "O que é Price Action?",
  "2-1": "Oferta e Procura no Gráfico",
  "2-2": "Tendência de Alta (LTA)",
  "2-3": "Tendência de Baixa (LTB)",
  "2-4": "Prática: Suporte e Resistência em M5",
  "2-5": "Mercado Lateral e Consolidação",
  "2-6": "O Conceito de Suporte",
  "2-7": "O Conceito de Resistência",
  "2-8": "Como Traçar Suporte e Resistência",
  "2-9": "Zonas vs. Linhas Exatas",
  "2-10": "Identificando Zonas Fortes e Fracas",
  "2-11": "Entendendo o Rompimento (Breakout)",
  "2-12": "Como Evitar Falsos Rompimentos",
  "2-13": "Inversão de Polaridade",
  "2-14": "O Conceito de Pullback",
  "2-15": "Estratégia: Pullback de Alta",
  "2-16": "Estratégia: Pullback de Baixa",
  "2-17": "Traçando LTAs com Precisão",
  "2-18": "Traçando LTBs com Precisão",
  "2-19": "Operando Toques na LTA e LTB",
  "2-20": "Prática: Simulação de Pullback",
  "2-21": "Retração de Vela em M5/M15",
  "2-22": "Escolhendo o Timeframe Ideal",
  "2-23": "Revisão de Price Action",
  "2-24": "Desafio de Leitura Gráfica",

  // Módulo 3 (51-75)
  "3-0": "Psicologia dos Candlesticks",
  "3-1": "O Padrão Martelo (Hammer)",
  "3-2": "O Padrão Enforcado",
  "3-3": "Estrela Cadente (Shooting Star)",
  "3-4": "Prática: Padrões de Reversão de 1 Vela",
  "3-5": "Martelo Invertido",
  "3-6": "Engolfo de Alta",
  "3-7": "Engolfo de Baixa",
  "3-8": "Doji: O Sinal de Indecisão",
  "3-9": "Tipos de Doji e Aplicações",
  "3-10": "Pinbar: A Rejeição Extrema",
  "3-11": "Harami de Alta",
  "3-12": "Harami de Baixa",
  "3-13": "Estrela da Manhã (Morning Star)",
  "3-14": "Estrela da Tarde (Evening Star)",
  "3-15": "Três Soldados de Esquerda",
  "3-16": "Três Corvos Negros",
  "3-17": "Prática: Padrões de 2 e 3 Velas",
  "3-18": "Vela de Força (Marubozu)",
  "3-19": "Vela de Exaustão de Mercado",
  "3-20": "Piercing Line e Dark Cloud",
  "3-21": "Topo Duplo (M) e Fundo Duplo (W)",
  "3-22": "Ombro-Cabeça-Ombro (OCO)",
  "3-23": "Flâmulas e Bandeiras",
  "3-24": "Revisão Completa de Padrões",

  // Módulo 4 (76-100)
  "4-0": "Introdução aos Indicadores",
  "4-1": "Médias Móveis (SMA e EMA)",
  "4-2": "Identificando Tendência com Médias",
  "4-3": "Cruzamento de Médias Móveis",
  "4-4": "Prática: Filtrando Entradas com RSI",
  "4-5": "O Indicador RSI",
  "4-6": "Sobrecompra e Sobrevenda no RSI",
  "4-7": "Divergência Oculta no RSI",
  "4-8": "Anatomia das Bandas de Bollinger",
  "4-9": "Operando Toques nas Bandas",
  "4-10": "Squeeze das Bandas de Bollinger",
  "4-11": "Oscilador Estocástico",
  "4-12": "Indicador MACD na Prática",
  "4-13": "As Linhas de Fibonacci",
  "4-14": "Como Traçar Fibonacci Corretamente",
  "4-15": "Os Níveis Chave: 38.2%, 50%, 61.8%",
  "4-16": "Operando a Retração em 61.8%",
  "4-17": "Confluência: Combinando Sinais",
  "4-18": "Prática: Operação com 3 Confluências",
  "4-19": "Fractais de Williams",
  "4-20": "Volume e Confirmações",
  "4-21": "Estratégias Probabilísticas: Mitos e Verdades",
  "4-22": "Montando seu Template de Indicadores",
  "4-23": "Revisão Geral de Indicadores",
  "4-24": "Masterclass de Confluência",

  // Módulo 5 (101-125)
  "5-0": "Por que 95% dos Traders Perdem?",
  "5-1": "Matemática: Payout vs. Win Rate",
  "5-2": "Definição do Capital de Risco",
  "5-3": "Divisão de Banca e Lotes",
  "5-4": "Prática: Calculando Risco e Retorno",
  "5-5": "Gestão Fixa (1% a 3%)",
  "5-6": "O Perigo do Martingale",
  "5-7": "Gestão Soros de Alavancagem",
  "5-8": "SorosGale e Variações",
  "5-9": "Definindo o Stop Loss Diário",
  "5-10": "Definindo o Stop Win Diário",
  "5-11": "Respeitando os Limites Diários",
  "5-12": "O Perigo do Revenge Trading",
  "5-13": "Lidando com Sequências de Vitória",
  "5-14": "Lidando com Sequências de Loss",
  "5-15": "Criando seu Diário de Trader",
  "5-16": "Análise Semanal de Performance",
  "5-17": "Evitando o Overtrading",
  "5-18": "A Rotina Pré-Mercado Perfeita",
  "5-19": "Construindo seu Plano de Trading",
  "5-20": "Transição para Conta Real",
  "5-21": "Controlando a Ansiedade Operacional",
  "5-22": "A Mente do Trader Consistente",
  "5-23": "Revisão da Jornada BinaryMaster",
  "5-24": "Simulação Geral Pré-Graduação",
};

// Gerador dinâmico da estrutura completa de passos para as 125 lições
export const LESSONS = {};

Object.keys(LESSON_TITLES).forEach((key) => {
  const [modId, lessonIdx] = key.split("-").map(Number);
  const title = LESSON_TITLES[key];

  LESSONS[key] = {
    title,
    steps: [
      {
        type: "info",
        level: `Módulo ${modId} · Lição ${lessonIdx + 1}`,
        title: title,
        body: `Bem-vindo à lição de "${title}". Vamos explorar os conceitos fundamentais desta técnica e como aplicá-la estrategicamente no gráfico de Opções Binárias.`,
        pipTip: "Analise sempre o contexto geral do gráfico antes de tomar uma decisão de entrada!",
      },
      {
        type: "chart-info",
        level: "Análise Gráfica",
        title: "Observando o Gráfico",
        body: "Observe a formação dos candles e o comportamento das movimentações no gráfico abaixo:",
        chart: {
          candles: [
            { open: 40, high: 55, low: 35, close: 50 },
            { open: 50, high: 60, low: 45, close: 42 },
            { open: 42, high: 48, low: 25, close: 30 },
            { open: 30, high: 65, low: 28, close: 60 },
          ],
          lines: [{ y: 30, color: "#10B981", label: "Zona Estratégica" }],
        },
      },
      {
        type: "mcq",
        level: "Teste de Conhecimento",
        question: `Considerando o conceito de "${title}", qual a atitude correta do trader no cenário atual?`,
        options: [
          "Aguardar a confirmação do padrão e respeitar a gestão de risco.",
          "Entrar imediatamente com 100% da banca.",
          "Ignorar a tendência principal do mercado.",
        ],
        correct: 0,
        explain: "A paciência e o respeito ao seu gerenciamento são cruciais para a consistência no trading.",
      },
      {
        type: "chart",
        level: "Decisão Operacional",
        question: "Com base no padrão observado no gráfico, qual ordem você executaria?",
        chart: {
          candles: [
            { open: 30, high: 45, low: 25, close: 40 },
            { open: 40, high: 50, low: 38, close: 48 },
            { open: 48, high: 52, low: 20, close: 25 },
            { open: 25, high: 60, low: 22, close: 58 },
          ],
          lines: [{ y: 22, color: "#3B82F6", label: "Suporte Principal" }],
        },
        correct: "CALL",
        explain: "A rejeição no suporte seguida de uma forte vela de força compradora indica um sinal claro de CALL.",
      },
    ],
  };
});
